apiVersion: v1
kind: PersistentVolumeClaim # 영구 스토리지 생성을 요청하는 객체
metadata:
  name: mes-share-pvc # PVC 이름
spec:
  storageClassName: nfs # ReclaimPolicy : delete 로 설정되어 있으므로 pvc 삭제시 물리스토리지의 데이터도 삭제됨
  accessModes:
    - ReadWriteMany # 스토리지 액세스 모드
  resources:
    requests:
      storage: 10Gi # 용량은 지정되어있지만 실제로 10G 이상 사용 가능

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restservice # 배포 이름
  labels:
    app: restservice # 배포 이름
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restservice # 배포 이름
  template:
    metadata:
      labels:
        app: restservice # 배포 이름
    spec:
      volumes:
      - name: data-volume # 볼륨명
        persistentVolumeClaim:
          claimName: mes-share-pvc
      containers:
      - name: restservice  # 컨테이너 이름
        image: "openjdk:18-jdk-alpine3.15" # 이미지명 
        imagePullPolicy: Always
#        command: ["sleep"]
#        args: ["infinity"]
        command: ["java"]
        args: ["-jar", "-Dspring.profiles.active=k8s", "/data/RestService-0.0.1-SNAPSHOT.jar"]
        ports: # 컨테이너 내부에서 사용하는 포트 명시
        - name: web
          containerPort: 8080
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
        volumeMounts: # 영구 저장할 볼륨 (디렉토리) 설정
        - name: data-volume # 위에서 명시한 볼륨명 지정
          mountPath: /data # 서비스에서 필요한 경로 지정

---
apiVersion: v1
kind: Service
metadata:
  name: restservice-stateless-svc # 서비스 이름
spec:
  selector:
    app: apigateway # 연결할 Deployment의 이름
  clusterIP: None # 매우 중요! stateless 서비스로 생성
  ports:
  - port: 8080
    name: web
    protocol: TCP
