server:
  port: 9000

spring:
  config:
    activate:
      on-profile: k8s
      
  application:
    name: service-discovery 
    
eureka:
  instance:
    hostname: ${HOSTNAME}.eureka
    
  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka:9000/eureka/, http://eureka-1.eureka:9000/eureka/, http://eureka-2.eureka:9000/eureka/
