spring:
  application:
    name: rest-service
  datasource:
    url: 'jdbc:mariadb://localhost:3306/rest?autoReconnect=true'
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  
  cloud:
    bootstrap:
      enabled: true

data: local
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,conditions,env,refresh
  
eureka:
  instance:
    prefer-ip-address: true

  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka:9000/eureka/, http://eureka-1.eureka:9000/eureka/, http://eureka-2.eureka:9000/eureka/
      
server:
  port: 8080