server:
  port: 8080
---
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: API Gateway
            preLogger: true
            postLogger: true
      routes:
        - id: user-svc
          uri: lb://REST-SERVICE
          predicates:
            - Path=/user/**
---  
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka:9000/eureka/, http://eureka-1.eureka:9000/eureka/, http://eureka-2.eureka:9000/eureka/